version: "2.4"
services:
  #Node Service
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: client-${APP_NAME}
    env_file: .env
    ports:
      - 80:3000
      - 3000:3000
    volumes:
      - .:/node/app:delegated
      - /node/app/node_modules
    networks:
      - containers_net

#Docker Networks
networks:
  containers_net:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
